/**
 * Deterministic serialization of generated fixtures:
 * spec/fixtures/generated/<scenario>.json (fixture-file format, one case per line)
 * and spec/fixtures/generated/summary.json.
 */
import { SCENARIOS } from "./scenarios/index.js";
import { type Config, type GeneratedCase, type ScenarioResult, loadConfig, runScenario } from "./scenario.js";

/** Invisible / format / combining code points are written as \uXXXX so diffs stay readable. */
const INVISIBLE_RANGES: [number, number][] = [
  [0x7f, 0xa0], [0xad, 0xad], [0x300, 0x36f], [0x61c, 0x61c], [0x115f, 0x1160], [0x17b4, 0x17b5],
  [0x180e, 0x180e], [0x2000, 0x200f], [0x2028, 0x202f], [0x205f, 0x206f], [0x3000, 0x3000], [0x3164, 0x3164],
  [0xfe00, 0xfe0f], [0xfeff, 0xfeff], [0xffa0, 0xffa0], [0xfff0, 0xfffb],
];
const hex = (n: number) => `\\u${n.toString(16).padStart(4, "0")}`;
const INVISIBLE = new RegExp(`[${INVISIBLE_RANGES.map(([a, b]) => `${hex(a)}-${hex(b)}`).join("")}]`, "g");

export function jsonLine(value: unknown): string {
  return JSON.stringify(value).replace(INVISIBLE, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}

/** The most common per-case options of a scenario become the file's `defaults.options`. */
function defaultOptions(cases: GeneratedCase[]): string {
  const counts = new Map<string, number>();
  for (const c of cases) {
    const k = JSON.stringify(c.options);
    counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  let best = "{}";
  let n = 0;
  for (const [k, v] of [...counts].sort(([a], [b]) => (a < b ? -1 : 1))) {
    if (v > n) {
      best = k;
      n = v;
    }
  }
  return best;
}

function caseObject(c: GeneratedCase, defaults: string): Record<string, unknown> {
  const o: Record<string, unknown> = { id: c.id, input: c.input };
  // `options` equal to defaults.options is omitted (same effective options, shallow merge).
  if (JSON.stringify(c.options) !== defaults) o.options = c.options;
  o.expected = c.expected;
  o.rules = c.rules;
  return o;
}

export function serializeScenario(r: ScenarioResult): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  "$schema": "../../schema/fixture-file.schema.json",`);
  lines.push(`  "description": ${jsonLine(`GENERATED by spec/generator (scenario ${r.name}) \u2014 do not edit by hand. ${r.description}`)},`);
  const defaults = defaultOptions(r.cases);
  lines.push(`  "defaults": { "fn": "parse", "options": ${defaults} },`);
  lines.push(`  "cases": [`);
  r.cases.forEach((c, i) => {
    lines.push(`    ${jsonLine(caseObject(c, defaults))}${i < r.cases.length - 1 ? "," : ""}`);
  });
  lines.push("  ]");
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

export function serializeSummary(results: ScenarioResult[], cfg: Config): string {
  const total = results.reduce((a, r) => a + r.cases.length, 0);
  const summary = {
    generator: "@trackparse/fixture-gen",
    seed: cfg.seed,
    total,
    scenarios: Object.fromEntries(
      results.map((r) => [
        r.name,
        {
          file: `${r.name}.json`,
          cases: r.cases.length,
          ...r.stats,
        },
      ]),
    ),
  };
  return `${JSON.stringify(summary, null, 2)}\n`;
}

export interface Generated {
  results: ScenarioResult[];
  /** file name (relative to spec/fixtures/generated) → content */
  files: Map<string, string>;
}

export function generateAll(cfg: Config = loadConfig()): Generated {
  const results = SCENARIOS.map((s) => runScenario(s, cfg));
  const files = new Map<string, string>();
  for (const r of results) files.set(`${r.name}.json`, serializeScenario(r));
  files.set("summary.json", serializeSummary(results, cfg));
  return { results, files };
}
